model:
  base_learning_rate: 1.2e-6
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: caption
    image_size: 64
    channels: 4
    cond_stage_trainable: true   # Note: different from the one we trained before
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: False
    unfreeze_model: True
    model_lr: 1.1e-6
    #use_scheduler: True
    scheduler_config: 
      target: ldm.lr_scheduler.EveryDreamScheduler
      params:
        f_start: 5.0e-1 # starting LR multiplier
        warm_up_steps: 50 # number of steps to warm up to f_start before decaying LR
        f_max: 1.0 # maximum LR multiplier
        f_min: 5.0e-1 # minimum LR multiplier
        steps_to_min: 10000 # number of steps to decay from f_max to f_min
        verbosity_interval: 200 # how often to print LR multiplier (steps)

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: True
        legacy: False

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 512
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenCLIPEmbedder

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 6 
    num_workers: 12
    wrap: falsegit
    train:
      target: ldm.data.every_dream.EveryDreamBatch
      params:
        repeats: 35   # rough suggestions: 5 with 5000+ images, 15 for 1000 images, use micro yaml for <100
        debug_level: 1   # 1 to print if images are dropped due to multiple-aspect ratio image batching
        conditional_dropout: 0.04   # experimental, likelihood to drop the caption, may help with poorly captioned images
        resolution: 512  # defines max pixels for all aspects, 512, 576, 640, 704, or 768
    validation:
      target: ldm.data.ed_validate.EDValidateBatch
      params:
        repeats: 1
    test:
      target: ldm.data.ed_validate.EDValidateBatch
      params:
        repeats: 0.1

lightning:
  modelcheckpoint:
    params:
      every_n_epochs: 1
      #every_n_train_steps: 1500 # can only use every_n_epochs OR every_n_train_steps, suggest you stick with epochs
      save_last: True
      save_top_k: 99
      filename: "{epoch:02d}-{step:05d}"
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 400
        max_images: 16
        increase_log_steps: False

  trainer:
    benchmark: True
    max_epochs: 2
    max_steps: 99000  # better to end on epochs not steps, especially with >500 images to ensure even distribution, but you can set this if you really want...
    check_val_every_n_epoch: 1
    gpus: 0,
